INSERT INTO permissao (nome) VALUES ("CARDAPIO_GET"), ("CARDAPIO_POST"), ("CARDAPIO_PUT"), ("CARDAPIO_DELETE");
INSERT INTO permissao (nome) VALUES ("RECEITA_GET"), ("RECEITA_POST"), ("RECEITA_PUT"), ("RECEITA_DELETE");
INSERT INTO permissao (nome) VALUES ("INGREDIENTE_GET"), ("INGREDIENTE_POST"), ("INGREDIENTE_PUT"), ("INGREDIENTE_DELETE");
INSERT INTO permissao (nome) VALUES ("RECEITAINGREDIENTE_GET"), ("RECEITAINGREDIENTE_POST"), ("RECEITAINGREDIENTE_DELETE");

-- INSERT INTO perfil (nome, permissoes) VALUES ("ADMIN", ARRAY['CARDAPIO_GET', 'CARDAPIO_POST', 'CARDAPIO_PUT', 'CARDAPIO_DELETE', 'RECEITA_GET', 'RECEITA_POST', 'RECEITA_PUT', 'RECEITA_DELETE', 'INGREDIENTE_GET', 'INGREDIENTE_POST', 'INGREDIENTE_PUT', 'INGREDIENTE_DELETE', 'RECEITAINGREDIENTE_GET', 'RECEITAINGREDIENTE_POST', 'RECEITAINGREDIENTE_DELETE']);
